In [32]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop

feature_names =  ['party','handicapped-infants', 'water-project-cost-sharing', 
                    'adoption-of-the-budget-resolution', 'physician-fee-freeze',
                    'el-salvador-aid', 'religious-groups-in-schools',
                    'anti-satellite-test-ban', 'aid-to-nicaraguan-contras',
                    'mx-missle', 'immigration', 'synfuels-corporation-cutback',
                    'education-spending', 'superfund-right-to-sue', 'crime',
                    'duty-free-exports', 'export-administration-act-south-africa']

voting_data = pd.read_csv('MLCourse/house-votes-84.data.txt', na_values=['?'], 
                          names = feature_names)
voting_data.head()

,party,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missle,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN
2,democrat,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y

In [33]:
voting_data.describe()

,party,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missle,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
count,435,423,387,424,424,420,424,421,420,413,428,414,404,410,418,407,331
unique,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
top,democrat,n,y,y,n,y,y,y,y,y,y,n,n,y,y,n,y
freq,267,236,195,253,247,212,272,239,242,207,216,264,233,209,248,233,269

In [34]:
voting_data.dropna(inplace=True)
voting_data.describe()

,party,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missle,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
count,232,232,232,232,232,232,232,232,232,232,232,232,232,232,232,232,232
unique,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
top,democrat,n,n,y,n,y,y,y,y,n,y,n,n,y,y,n,y
freq,124,136,125,123,119,128,149,124,119,119,128,152,124,127,149,146,189

In [35]:
voting_data.replace(('y','n'), (1, 0), inplace=True)
voting_data.replace(('democrat', 'republican'), (1,0), inplace=True)
voting_data.head()

,party,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missle,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
5,1,0,1,1,0,1,1,0,0,0,0,0,0,1,1,1,1
8,0,0,1,0,1,1,1,0,0,0,0,0,1,1,1,0,1
19,1,1,1,1,0,0,0,1,1,1,0,1,0,0,0,1,1
23,1,1,1,1,0,0,0,1,1,1,0,0,0,0,0,1,1
25,1,1,0,1,0,0,0,1,1,1,1,0,0,0,0,1,1

In [36]:
all_features = voting_data[feature_names].drop('party', axis=1).values
all_classes = voting_data['party']

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(all_features, all_classes, test_size=0.2, random_state=420)
X_train.shape

(185, 16)

In [92]:
model = Sequential()
model.add(Dense(64, activation='relu', kernel_initializer='normal', input_dim=16))
model.add(Dense(32, activation='relu', kernel_initializer='normal'))
model.add(Dense(1, activation='sigmoid'))

In [93]:
model.compile(loss='binary_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

In [95]:
history = model.fit(X_train, y_train,
                    batch_size=30,
                    epochs=20,
                    verbose=2,
                    validation_data=(X_test, y_test)
                   )

Epoch 1/20
7/7 - 0s - loss: 0.0439 - accuracy: 0.9946 - val_loss: 0.0893 - val_accuracy: 0.9362
Epoch 2/20
7/7 - 0s - loss: 0.0397 - accuracy: 0.9946 - val_loss: 0.0908 - val_accuracy: 0.9362
Epoch 3/20
7/7 - 0s - loss: 0.0390 - accuracy: 0.9892 - val_loss: 0.0984 - val_accuracy: 0.9362
Epoch 4/20
7/7 - 0s - loss: 0.0379 - accuracy: 0.9892 - val_loss: 0.0949 - val_accuracy: 0.9362
Epoch 5/20
7/7 - 0s - loss: 0.0378 - accuracy: 0.9838 - val_loss: 0.0924 - val_accuracy: 0.9362
Epoch 6/20
7/7 - 0s - loss: 0.0377 - accuracy: 0.9946 - val_loss: 0.0982 - val_accuracy: 0.9362
Epoch 7/20
7/7 - 0s - loss: 0.0370 - accuracy: 0.9838 - val_loss: 0.0938 - val_accuracy: 0.9574
Epoch 8/20
7/7 - 0s - loss: 0.0318 - accuracy: 0.9946 - val_loss: 0.0940 - val_accuracy: 0.9362
Epoch 9/20
7/7 - 0s - loss: 0.0334 - accuracy: 0.9892 - val_loss: 0.1268 - val_accuracy: 0.9574
Epoch 10/20
7/7 - 0s - loss: 0.0358 - accuracy: 0.9838 - val_loss: 0.1085 - val_accuracy: 0.9574
Epoch 11/20
7/7 - 0s - loss: 0.0309 - accuracy: 0.9892 - val_loss: 0.1034 - val_accuracy: 0.9362
Epoch 12/20
7/7 - 0s - loss: 0.0301 - accuracy: 0.9946 - val_loss: 0.0972 - val_accuracy: 0.9362
Epoch 13/20
7/7 - 0s - loss: 0.0296 - accuracy: 0.9946 - val_loss: 0.1056 - val_accuracy: 0.9574
Epoch 14/20
7/7 - 0s - loss: 0.0344 - accuracy: 0.9838 - val_loss: 0.1037 - val_accuracy: 0.9362
Epoch 15/20
7/7 - 0s - loss: 0.0267 - accuracy: 0.9892 - val_loss: 0.1101 - val_accuracy: 0.9574
Epoch 16/20
7/7 - 0s - loss: 0.0274 - accuracy: 0.9946 - val_loss: 0.1182 - val_accuracy: 0.9574
Epoch 17/20
7/7 - 0s - loss: 0.0259 - accuracy: 0.9946 - val_loss: 0.1020 - val_accuracy: 0.9362
Epoch 18/20
7/7 - 0s - loss: 0.0277 - accuracy: 0.9946 - val_loss: 0.1188 - val_accuracy: 0.9574
Epoch 19/20
7/7 - 0s - loss: 0.0239 - accuracy: 0.9946 - val_loss: 0.1060 - val_accuracy: 0.9362
Epoch 20/20
7/7 - 0s - loss: 0.0227 - accuracy: 0.9946 - val_loss: 0.1087 - val_accuracy: 0.9362

In [89]:
def create_model():
    model = Sequential()
    model.add(Dense(64, activation='relu', kernel_initializer='normal', input_dim=16))
    model.add(Dense(32, activation='relu', kernel_initializer='normal'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])
    return model

In [90]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

estimator = KerasClassifier(build_fn=create_model, epochs=100, verbose=0)

scores = cross_val_score(estimator, all_features, all_classes, cv=10)

In [91]:
scores.mean()

0.9527173936367035